const fs=require('fs'), path=require('path');
const SRC=path.join(__dirname,'src'), OUT=path.join(__dirname,'_site');
const read=p=>fs.readFileSync(p,'utf8');
const data=n=>JSON.parse(read(path.join(SRC,'_data',n+'.json')));
function esc(s=''){return String(s).replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));}
function frontMatter(text){const m=text.match(/^---\n([\s\S]*?)\n---\n([\s\S]*)$/); if(!m) return [{},text]; const meta={}; m[1].split('\n').forEach(l=>{const i=l.indexOf(':'); if(i>0) meta[l.slice(0,i).trim()]=l.slice(i+1).trim();}); return [meta,m[2]];}
function markdown(s){
  const lines=s.split(/\n/), out=[]; let para=[], list=false;
  const flush=()=>{if(para.length){out.push('<p>'+inline(para.join(' '))+'</p>'); para=[];} if(list){out.push('</ul>');list=false;}};
  function inline(t){return t.replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/\[(.+?)\]\((.+?)\)/g,'<a href="$2">$1</a>');}
  for(const raw of lines){const l=raw.trim(); if(!l){flush();continue;} let m;
    // Source pages use complete HTML blocks on one line. Emit them directly so
    // block elements are never wrapped in invalid paragraph tags.
    if(l.startsWith('<') && l.endsWith('>')){flush();out.push(raw);continue;}
    if((m=l.match(/^(#{2,4})\s+(.+)$/))){flush();out.push(`<h${m[1].length}>${inline(m[2])}</h${m[1].length}>`);}
    else if((m=l.match(/^>\s+(.+)$/))){flush();out.push(`<blockquote>${inline(m[1])}</blockquote>`);}
    else if((m=l.match(/^[-*]\s+(.+)$/))){if(!list){flush();out.push('<ul>');list=true;} out.push('<li>'+inline(m[1])+'</li>');}
    else para.push(l);
  } flush(); return out.join('\n');
}
function schemaMarkup(meta,current,site){
 const image=site.url+'/assets/images/chalapathi-koneni.webp';
 const sameAs=[site.linkedin,site.github,site.scholar,site.orcid].filter(Boolean);
 const person={"@type":"Person","@id":site.url+'/#person',"name":"Chalapathi Koneni","url":site.url,"image":image,"jobTitle":"Senior Data Engineering Leader","description":site.description,"sameAs":sameAs,"knowsAbout":["Data engineering","Data quality","Distributed data systems","Cloud analytics","Observability","Applied AI","Marketing measurement data systems"]};
 const graph=[];
 if(current==='/') graph.push({"@type":"ProfilePage","@id":site.url+'/#profilepage',"url":site.url+'/',"name":"Chalapathi Koneni | Data Engineering, Data Quality & Distributed Systems","mainEntity":{"@id":site.url+'/#person'},"about":{"@id":site.url+'/#person'}});
 graph.push(person);
 if(current!=='/'){
   const label=(meta.title||'').split('|')[0].trim();
   graph.push({"@type":"BreadcrumbList","itemListElement":[{"@type":"ListItem","position":1,"name":"Home","item":site.url+'/'},{"@type":"ListItem","position":2,"name":label,"item":site.url+current}]});
 }
 if(current.startsWith('/notes/')||current.startsWith('/research/')||current.startsWith('/case-studies/')){
   graph.push({"@type":"Article","headline":meta.title,"description":meta.description||site.description,"author":{"@id":site.url+'/#person'},"mainEntityOfPage":site.url+current,"image":site.url+'/assets/social-card.png'});
 }
 return '<script type="application/ld+json">'+JSON.stringify({"@context":"https://schema.org","@graph":graph})+'</script>';
}
function renderPage(meta, body, current){
 const site=data('site'), nav=data('navigation'), layout=read(path.join(SRC,'_includes','layout.html'));
 const links=nav.map(n=>`<a${n.url===current?' aria-current="page"':''} href="${n.url}">${esc(n.label)}</a>`).join('');
 const canonical=site.url+(current==='/'?'/':current);
 const rawTitle=meta.title||'Home';
 const pageTitle=rawTitle.includes('|')?rawTitle:(current==='/'?site.name:`${rawTitle} | ${site.name}`);
 const ogType=(current.startsWith('/notes/')||current.startsWith('/research/')||current.startsWith('/case-studies/'))?'article':'website';
 return layout.replaceAll('{{TITLE}}',esc(rawTitle)).replaceAll('{{PAGE_TITLE}}',esc(pageTitle)).replaceAll('{{DESCRIPTION}}',esc(meta.description||site.description)).replaceAll('{{CANONICAL}}',canonical).replaceAll('{{SITE_NAME}}',esc(site.name)).replaceAll('{{TAGLINE}}',esc(site.tagline)).replaceAll('{{SITE_URL}}',site.url).replaceAll('{{NAVIGATION}}',links).replaceAll('{{FOOTER_NAV}}',links).replaceAll('{{FOOTER_NOTE}}',esc(site.footerNote)).replaceAll('{{CONTENT}}',body).replaceAll('{{LINKEDIN}}',site.linkedin).replaceAll('{{SCHOLAR}}',site.scholar||'').replaceAll('{{ORCID}}',site.orcid||'').replaceAll('{{OG_TYPE}}',ogType).replaceAll('{{SCHEMA}}',schemaMarkup(meta,current,site));
}
function homeFeatures(){
 const eng=data('engineering').filter(x=>x.visible).sort((a,b)=>a.order-b.order).slice(0,3);
 const res=data('research').filter(x=>x.public&&x.verified).sort((a,b)=>a.order-b.order).slice(0,3);
 const proof=data('evidence').filter(x=>x.visible&&x.homepageFeature&&x.verification==='direct').sort((a,b)=>b.priority-a.priority).slice(0,4);
 const talk=data('speaking').find(x=>x.visible);
 return `<section class="home-work"><div class="wrap"><div class="section-heading compact"><div><div class="eyebrow">Selected engineering work</div><h2>Engineering patterns that travel across systems.</h2></div><p>Case studies focused on the decision, the tradeoff, and what the system taught us.</p></div><div class="feature-grid">${eng.map((x,i)=>`<article class="feature-card ${i===0?'feature-card-primary':''}"><span class="tag">Case study</span><h3>${esc(x.title)}</h3><p>${esc(x.summary)}</p><a href="/case-studies/${x.slug}.html">Read the case study →</a></article>`).join('')}</div></div></section>
 <section class="home-research"><div class="wrap"><div class="section-heading compact"><div><div class="eyebrow">Selected research</div><h2>Production failures, made testable.</h2></div><p>Published and accepted work on silent corruption, anomaly detection, and evidence quality.</p></div><div class="research-list">${res.map(x=>`<article><div><span class="tag">${esc(x.status)} · ${esc(x.venue||'Research')}</span><h3>${esc(x.title)}</h3><p>${esc(x.question)}</p></div><div class="research-links"><a href="/research/${x.slug}.html">Research note →</a>${x.url?`<a href="${x.url}" rel="noopener noreferrer">${esc(x.linkLabel||'Source')} ↗</a>`:''}</div></article>`).join('')}</div></div></section>
 <section class="recognition-band"><div class="wrap"><div class="recognition-head"><div><div class="eyebrow">Selected professional service</div><h2>Selected to review, lead, and shape technical programs.</h2><p>Invited roles that involve evaluating research, guiding technical programs, and supporting the quality of professional communities.</p></div><a class="recognition-all" href="/service.html">View service and official sources →</a></div><div class="recognition-list">${proof.map(x=>`<article class="recognition-row"><div class="recognition-index">${String(proof.indexOf(x)+1).padStart(2,'0')}</div><div><h3>${esc(x.title)}</h3><p class="recognition-role">${esc(x.role)}</p>${x.significance?`<p class="recognition-significance">${esc(x.significance)}</p>`:''}</div></article>`).join('')}</div></div></section>
 <section class="speaking-highlight"><div class="wrap speaking-inner"><div><div class="eyebrow">Professional service</div><h2>Reviewing research and evaluating technical innovation.</h2><p>Program committees, conference leadership, editorial review, and hackathon judging across research and student technology communities.</p></div><div class="speaking-cta"><a class="button ghost" href="/service.html">View professional service</a></div></div></section>
 ${talk?`<section class="speaking-highlight"><div class="wrap speaking-inner"><div><div class="eyebrow">Speaking</div><h2>${esc(talk.title)}</h2><p>${esc(talk.description)}</p></div><div class="speaking-cta"><a class="button ghost" href="/speaking.html">Selected talks</a></div></div></section>`:''}`;
}
function dataPages(){
 const pages=[];
 const eng=data('engineering').filter(x=>x.visible).sort((a,b)=>a.order-b.order);
 pages.push({file:'engineering.html',title:'Data Engineering & Data Quality Projects | Chalapathi Koneni',desc:'Data engineering and data quality case studies by Chalapathi Koneni, covering forecasting, cloud platforms, reconciliation, observability, and trustworthy AI.',body:`<header class="page-hero"><div class="wrap"><div class="eyebrow">Engineering</div><h1>Trustworthy data systems, explained through real engineering decisions.</h1><p>Each case study separates the problem, my contribution, why it mattered, and the lesson that transfers to other systems. Current-employer details remain intentionally general.</p></div></header><section><div class="wrap"><div class="record-grid">${eng.map(x=>`<article class="record"><span class="tag">Case study</span><h3>${esc(x.title)}</h3><p>${esc(x.summary)}</p><a href="/case-studies/${x.slug}.html">Read the case study →</a></article>`).join('')}</div></div></section>`});
 const res=data('research').filter(x=>x.public&&x.verified).sort((a,b)=>a.order-b.order);
 pages.push({file:'research.html',title:'Data Quality and Distributed Systems Research | Chalapathi Koneni',desc:'Public research by Chalapathi Koneni on data quality, silent corruption, anomaly detection, distributed systems, and evidence-quality telemetry.',body:`<header class="page-hero"><div class="wrap"><div class="eyebrow">Research</div><h1>Production problems, made testable.</h1><p>I am interested in questions that appear repeatedly in real systems: silent corruption, incomplete evidence, and observability under uncertainty.</p></div></header><section><div class="wrap"><div class="record-grid">${res.map(x=>`<article class="record"><span class="tag">${esc(x.status)}</span><h3>${esc(x.title)}</h3><p>${esc(x.question)}</p><div class="record-links"><a href="/research/${x.slug}.html">Read the research note →</a>${x.url?`<a href="${x.url}" rel="noopener noreferrer">${esc(x.linkLabel||'Source')} ↗</a>`:''}</div></article>`).join('')}</div></div></section><section><div class="wrap two-col"><div><div class="eyebrow">Method</div><h2>What makes a useful research question.</h2></div><div class="prose"><p>I start with a failure pattern that cannot be explained well by existing operational checks. The next step is to separate the local incident from the general mechanism: what conditions make the failure possible, what evidence would reveal it, and what intervention changes the outcome?</p><p>The aim is not to turn every production lesson into a grand theory. It is to make the reasoning clear enough that someone else can challenge it, reproduce it, or apply it in a different system.</p></div></div></section>`});
 const ns=data('notes').filter(x=>x.visible).sort((a,b)=>a.order-b.order);
 pages.push({file:'writing.html',title:'Data Engineering and Data Quality Articles | Chalapathi Koneni',desc:'Original articles by Chalapathi Koneni on data quality, distributed data systems, observability, cloud data platforms, and applied AI.',body:`<header class="page-hero"><div class="wrap"><div class="eyebrow">Notes</div><h1>Ideas in working form.</h1><p>Short essays on the engineering problems I keep returning to. These are written to clarify a point of view, not to manufacture a stream of content.</p></div></header><section><div class="wrap"><div class="record-grid">${ns.map(x=>`<article class="record"><span class="tag">Engineering note</span><h3>${esc(x.title)}</h3><p>${esc(x.summary)}</p><a href="/notes/${x.slug}.html">Read →</a></article>`).join('')}</div></div></section>`});
 const sp=data('speaking').filter(x=>x.visible);
 pages.push({file:'speaking.html',title:'Data Engineering and AI Speaker | Chalapathi Koneni',desc:'Selected keynotes, invited sessions, and talks by Chalapathi Koneni on data engineering, data quality, distributed systems, and applied AI.',body:`<header class="page-hero"><div class="wrap"><div class="eyebrow">Speaking</div><h1>Ideas become clearer when they are challenged in public.</h1><p>Selected keynotes, invited sessions, and engineering talks on data quality, AI reliability, large-scale data platforms, and operational trust.</p></div></header><section><div class="wrap"><div class="timeline">${sp.map(x=>`<article><div class="eyebrow">${esc(x.year)}</div><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p>${x.audience?`<p class="talk-meta"><strong>Audience:</strong> ${esc(x.audience)}</p>`:''}${x.takeaway?`<p class="talk-takeaway"><strong>Key takeaway:</strong> ${esc(x.takeaway)}</p>`:''}${x.url?`<a href="${x.url}" rel="noopener noreferrer">${esc(x.linkLabel||'Official page')} ↗</a>`:''}</article>`).join('')}</div></div></section>`});
 const ev=data('evidence').filter(x=>x.visible).sort((a,b)=>b.priority-a.priority);
 const groups=['Program Committee','Leadership','Judging','Editorial','Recognition'];
 pages.push({file:'service.html',title:'Technical Reviewer and Program Committee Service | Chalapathi Koneni',desc:'Selected program committee, technical-review, conference-leadership, editorial, and innovation-judging service by Chalapathi Koneni.',body:`<header class="page-hero"><div class="wrap"><div class="eyebrow">Professional service</div><h1>Reviewing, judging, and technical leadership.</h1><p>Selected roles across research conferences, academic programs, editorial review, and innovation events. Links identify the source they lead to rather than implying that every event page verifies the role.</p></div></header><section><div class="wrap"><div class="service-stack">${groups.map(g=>{const items=ev.filter(x=>x.category===g);return items.length?`<div class="service-group"><div class="service-group-title"><span>${esc(g)}</span></div><div class="service-list">${items.map(x=>`<article class="service-row"><div><h3>${esc(x.title)}</h3><p>${esc(x.role)} · ${esc(x.year)}</p>${x.significance?`<p class="service-significance">${esc(x.significance)}</p>`:''}</div><div>${x.url?`<a class="source-link ${x.verification==='direct'?'source-direct':''}" href="${x.url}" rel="noopener noreferrer">${esc(x.linkLabel||'Source')} ↗</a>`:'<span class="source-muted">Role listed without external source</span>'}</div></article>`).join('')}</div></div>`:''}).join('')}</div></div></section>`});
 const tl=data('timeline');
 pages.push({file:'timeline.html',title:'Timeline',desc:'Career timeline from enterprise transaction systems to trustworthy AI.',body:`<header class="page-hero"><div class="wrap"><div class="eyebrow">Timeline</div><h1>A career shaped by the same question in different systems.</h1><p>The path from transaction platforms to trustworthy AI was not a sudden change of field. Each stage exposed a deeper version of the problem of reliable evidence.</p></div></header><section><div class="wrap"><div class="timeline">${tl.map(x=>`<article><div class="eyebrow">${esc(x.period)}</div><h3>${esc(x.title)}</h3><p>${esc(x.description)}</p></article>`).join('')}</div></div></section>`});
 pages.push({file:'cv.html',title:'Curriculum Vitae',desc:'A compact record of experience, research, speaking, and professional service.',body:`<header class="page-hero"><div class="wrap"><div class="eyebrow">Curriculum vitae</div><h1>A compact professional record.</h1><p>Experience, research, speaking, and professional service in one place.</p></div></header><section><div class="wrap two-col"><div><div class="eyebrow">Profile</div><h2>Chalapathi Koneni</h2><p>Senior Data Engineering Leader<br>Cumming, Georgia, United States</p><p>Data engineering leader with more than twenty years of experience across enterprise decision systems, distributed data platforms, data quality, observability, and applied AI.</p><p><a href="${data('site').linkedin}" rel="noopener noreferrer">LinkedIn ↗</a> · <a href="/contact.html">Contact</a></p></div><div><div class="eyebrow">Experience</div><ul class="clean-list"><li><strong>Amazon</strong><br>Senior data engineering leadership in large-scale analytics and measurement systems</li><li><strong>Macy’s Technology</strong><br>Enterprise forecasting, replenishment, data integrity, and cloud modernization</li><li><strong>Apple</strong><br>Finance and supply-chain analytical systems</li><li><strong>Walmart, JCPenney, and Toys “R” Us</strong><br>Retail data, inventory, and enterprise integration</li></ul></div></div></section><section><div class="wrap two-col"><div><div class="eyebrow">Research</div><ul class="clean-list">${res.map(x=>`<li><strong>${esc(x.title)}</strong><br>${esc(x.status)}</li>`).join('')}</ul></div><div><div class="eyebrow">Service</div><ul class="clean-list">${ev.slice(0,8).map(x=>`<li><strong>${esc(x.title)}</strong><br>${esc(x.role)}</li>`).join('')}</ul></div></div></section>`});
 return pages;
}
function write(rel,content){const p=path.join(OUT,rel);fs.mkdirSync(path.dirname(p),{recursive:true});fs.writeFileSync(p,content);}
fs.rmSync(OUT,{recursive:true,force:true}); fs.mkdirSync(OUT,{recursive:true});
fs.cpSync(path.join(SRC,'assets'),path.join(OUT,'assets'),{recursive:true});
for(const dir of ['pages','case-studies','research','notes']){for(const f of fs.readdirSync(path.join(SRC,dir)).filter(x=>x.endsWith('.md'))){const [meta,raw]=frontMatter(read(path.join(SRC,dir,f))); let body=markdown(raw).replace('<p>{{HOME_FEATURES}}</p>',homeFeatures()).replace('{{HOME_FEATURES}}',homeFeatures()); const current=meta.permalink==='index.html'?'/':'/'+meta.permalink; write(meta.permalink,renderPage(meta,body,current));}}
for(const p of dataPages()){write(p.file,renderPage({title:p.title,description:p.desc},p.body,'/'+p.file));}
write('404.html',renderPage({title:'Page not found',description:'The requested page could not be found.'},'<header class="page-hero"><div class="wrap"><div class="eyebrow">404</div><h1>That page is not here.</h1><p><a href="/">Return home →</a></p></div></header>','/404.html'));
write('robots.txt','User-agent: *\nAllow: /\nSitemap: '+data('site').url+'/sitemap.xml\n');
const html=[]; function walk(d,base=''){for(const f of fs.readdirSync(d)){const p=path.join(d,f),r=path.join(base,f); if(fs.statSync(p).isDirectory())walk(p,r);else if(f.endsWith('.html'))html.push(r);}} walk(OUT);
write('sitemap.xml','<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+html.filter(x=>x!=='404.html').map(x=>'  <url><loc>'+data('site').url+'/'+(x==='index.html'?'':x)+'</loc></url>').join('\n')+'\n</urlset>\n');
write('site.webmanifest',JSON.stringify({name:data('site').name,short_name:'Chalapathi Koneni',start_url:'/',display:'standalone',background_color:'#f5f2ea',theme_color:'#f5f2ea'},null,2));
console.log(`Built ${html.length} HTML pages in _site`);
